name: Teranet Roster

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 1 1,4,7,10 *' # Runs at 12:00 UTC on the 1st day of January, April, July, and October
    
jobs:
  generate-report:
    runs-on: self-hosted

    env:
      REDASH_URL: ${{ secrets.REDASH_URL }} # https://redash.rahb.ca
      API_KEY: ${{ secrets.REDASH_API_KEY }} # API key for Redash
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} # API key for SendGrid
      FROM_EMAIL: ${{ secrets.MPAC_FROM_EMAIL }} # Sender's email address
      TO_EMAILS: ${{ secrets.MPAC_TO_EMAILS }} # Recipients' email addresses
      # Non-sensitive information can be set directly
      QUERY_IDS: "124,126"
      TITLES: "RAHB Member Counts for Teranet, RAHB Non-Chargeable Members for Teranet"
      LOGO_URL: "https://s1.cdn.rahb.ca/rahbca/wp-content/uploads/2018/10/RAHB-logo_hztrans_video.png"
      TIMESTAMP_FORMAT: "%B %Y"
      SUBJECT: "Teranet (Geowarehouse) self-reporting"
      CONTENT: "Enclosed RAHB active members with RECO Numbers and Non-Chargeable admin members spreadsheet of August 2023 for Teranet (GeoWarehouse)."
      MODE: "xlsx-multi"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Report
      run: python main.py --now
